kind: pipeline
type: docker
name: default

workspace:
  path: /drone/src
steps:
  - name: scp
    image: appleboy/drone-scp
    settings:
      debug: true
      source:
        - ./
      host:
        from_secret: CURRENT_HOST
      username: root
      port: 22
      password:
        from_secret: SSH_PWD
      target: /data/app/cwk
